Imports part 2
NopeFoundry/nope.website pull request #3
Opened 2023-09-03 15:42 UTC by ubitux

It would be great if we could center the images horizontally and vertically though...

2023-09-03 20:40 UTC, mbouron approved these changes

2023-09-03 20:43 UTC, mbouron requested changes
LGTM. I'll address the details you mentioned so we can merge it (or let our seasoned expert do its magic).

2023-09-09 08:36 UTC, ubitux commented
Thanks for the fixes we should be good.

2023-09-09 09:22 UTC, mbouron approved these changes

2023-09-09 09:25 UTC, merged